services:
  database:
    container_name: sitestatus_db
    image: postgres:18.3
    restart: "no"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - sitestatus_network
    volumes:
      - postgres-data:/var/lib/postgresql

  engine-db:
    container_name: sitestatus_engine_db
    image: timescale/timescaledb:latest-pg18
    restart: "no"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${ENGINE_DB_USER}
      POSTGRES_PASSWORD: ${ENGINE_DB_PASSWORD}
      POSTGRES_DB: ${ENGINE_DB_NAME}
    networks:
      - sitestatus_network
    volumes:
      - engine-data:/var/lib/postgresql

  sqlserver:
    container_name: sitestatus_sql
    image: mcr.microsoft.com/mssql/server:2022-CU25-ubuntu-22.04
    restart: "no"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - sitestatus_network

  servicebus-emulator:
    container_name: sitestatus_sb_emulator
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:2.0.1
    restart: "no"
    volumes:
      - ./sb-config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - "5672:5672"
    environment:
      ACCEPT_EULA: "Y"
      SQL_SERVER: sqlserver
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    depends_on:
      - sqlserver
    networks:
      - sitestatus_network

volumes:
  postgres-data:
  engine-data:
  servicebus-data:

networks:
  sitestatus_network:
