services:
  database:
    container_name: sitestatus_db
    image: postgres:18.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - sitestatus_network
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    container_name: sitestatus_redis
    image: redis:8.6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6380:6379"
    networks:
      - sitestatus_network
    volumes:
      - redis-data:/data

  sqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - sitestatus_network

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - ./sb-config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      - ACCEPT_EULA=Y
      - SQL_SERVER=sqledge
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    depends_on:
      - sqledge
    networks:
      - sitestatus_network

volumes:
  postgres-data:
  redis-data:
  servicebus-data:

networks:
  sitestatus_network:
